name: backend CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
            with: 
                node-version: '16'
        - run: cd backend
        - run: npm install
        - run: npm run build

